CREATE TABlE department {
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL
};

CREATE TABLE role {
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    department_id INT NOT NULL,
    FOREIGN KEY (department_id) REFRENCES department(id) 
    ON DELETE CASCADE UPDATE CASCADE
 
};

CREATE TABLE employee {
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NOT NULL,
    manager_id INT NULL,
    FOREIGN KEY (role_id) REFRENCES role(id) 
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (manager_id) REFRENCES employee(id) 
    ON DELETE SET NULL ON UPDATE CASCADE
};